name: Publish to Nexus

on:
  push:
    branches:
      - master
env:
  groupId: com.yuanmai.protobuf
  artifactId: yuanmai-protobuf-java
  version: 21.1.1-SNAPSHOT
  nexus-repository: maven-snapshots

jobs:
  build-push-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Build and Deploy with Maven
        run: mvn deploy  -Dpassword=${{ secrets.password }} --file pom.xml -s settings.xml
